In [1]:
#1
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

[10 20 30 40 50]
1
(5,)
int64
5


In [6]:
#2
import numpy as np
arr1=np.arange(1,13)
print(arr1.reshape(3,4))

arr2=np.arange(1,25)
print(arr2.reshape(2,3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [9]:
#3
arr=np.zeros(5)
print(arr)
arr1=np.zeros((2,3))
print(arr1)
arr2=np.zeros((2,3,2))
print(arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [11]:
#4
arr=np.ones((2,3))
print(arr)
print(arr.ndim)
print(arr.size)

[[1. 1. 1.]
 [1. 1. 1.]]
2
6


In [12]:
#5
arr=np.full((3,4),7)
print(arr)
arr1=np.eye(4)
print(arr1)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
#6
arr=np.random.random(5)
print(arr)
arr1=np.random.random((2,3))
print(arr1)

[0.58655259 0.32275964 0.3826398  0.74894463 0.77666253]
[[0.80976684 0.09079189 0.54607206]
 [0.3036314  0.47055123 0.91340718]]


In [54]:
#7
arr=np.random.uniform(10,50,(3,3))
print(arr)

[[18.87972684 44.82929225 18.26876621]
 [46.74443632 29.53644755 34.46975452]
 [40.63631426 30.73671951 21.87202006]]


In [21]:
#8
arr=np.random.randn(2,4)
print(arr)

[[-0.08653766  1.43288608 -1.65325485 -1.35544402]
 [ 0.17738725 -0.37776587 -1.10698923 -1.19845257]]


In [24]:
#9
colors=np.array(["Red","Blue","Green","Yellow","Black"])
print(colors)
print(np.random.choice(colors,3))

['Red' 'Blue' 'Green' 'Yellow' 'Black']
['Black' 'Blue' 'Blue']


In [66]:
#10
arr=np.random.uniform(1,5,5)
np.random.seed(5)
print(arr)


[2.03639039 4.20998754 4.48193235 4.69099846 1.00885685]
[2.03639039 4.20998754 4.48193235 4.69099846 1.00885685]


In [83]:
#11
arr=np.linspace(5,50,5)
print(arr)
arr1=np.linspace(5,50,10)
print(arr1)

[ 5.   16.25 27.5  38.75 50.  ]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [108]:
#12
arr=np.array([10,20,30,40,50,60])
result=np.random.shuffle(arr)
print(result)
print(arr)
print("---------------")
arr1=np.array([10,20,30,40,50,60])
result1=np.random.permutation(arr1)
print(result1)
print(arr1)


None
[20 50 10 60 40 30]
---------------
[50 10 20 40 30 60]
[10 20 30 40 50 60]


In [94]:
#13
arr=np.linspace(0,100,6)
print(arr)

[  0.  20.  40.  60.  80. 100.]


In [113]:
#14
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
res1=arr.reshape((3,4))
print(res1)
res2=arr.reshape(12)
print(res2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [118]:
#15
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.T)
print(arr.reshape((2,1,3)))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [141]:
#16
arr=np.array([10,20,30,40,50])
print(arr.dtype)
print(arr.astype("float"))

int64
[10. 20. 30. 40. 50.]


In [142]:
#17
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print(arr[1,1])
print(arr[-1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
[70 80 90]


In [143]:
#18
arr=np.array([10,20,30,40,50])
print(arr)
result=np.insert(arr,2,25)
print(result)
result2=np.delete(result,3)
print(result2)
print(np.sum(result))
print(np.min(result))
print(np.max(result))
print(np.mean(result))

[10 20 30 40 50]
[10 20 25 30 40 50]
[10 20 25 40 50]
175
10
50
29.166666666666668


In [157]:
#19
marks=np.array([10,20,30,40,50])
print(np.var(marks))
print(np.std(marks))
print(np.percentile(marks,[25,75]))
print(np.argmax(marks))
print(np.argmin(marks))
print(np.log10(marks))

200.0
14.142135623730951
[20. 40.]
4
0
[1.         1.30103    1.47712125 1.60205999 1.69897   ]


In [161]:
#20
A=np.array([1,2,3])
B=np.array([4,5,6])
C=np.array([7,8,9])
print(np.concatenate((A,B)))
print("______________")
print(np.stack((A,B),axis=0))
print("______________")
print(np.stack((A,B),axis=1))
print("______________")
print(np.vstack((A,B,C)))
print("______________")
result=np.hstack((A,B,C))
print(result)
print("______________")
print(np.split(result,3))

[1 2 3 4 5 6]
______________
[[1 2 3]
 [4 5 6]]
______________
[[1 4]
 [2 5]
 [3 6]]
______________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
______________
[1 2 3 4 5 6 7 8 9]
______________
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
