In [ ]:
#1D
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)

[10 20 30 40 50]
1


In [ ]:
#2D
import numpy as np
arr=np.array([[10,20,30,40,50],[60,70,80,50,70]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[10 20 30 40 50]
 [60 70 80 50 70]]
2
(2, 5)


In [ ]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,100]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 100]]
2
(3, 3)


In [ ]:
#3D
import numpy as np
arr=np.array([
    [[10,20,30],[40,50,60]],[[10,35,67],[70,80,100]]
    ])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 10  35  67]
  [ 70  80 100]]]
3
(2, 2, 3)


In [ ]:
import numpy as np
arr=np.array(["Ravi","priya"])
print(arr)
print(arr.dtype)

['Ravi' 'priya']
<U5


In [ ]:
import numpy as np
arr=np.array([10,20,30.5,40,50])
print(arr)
print(arr.dtype)

[10.  20.  30.5 40.  50. ]
float64


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50],dtype=float)
print(arr)


[10. 20. 30. 40. 50.]


In [ ]:
#arange()-to return from a range
import numpy as np
arr=np.arange(1,10)
print(arr)


[1 2 3 4 5 6 7 8 9]


In [ ]:
#arange()
import numpy as np
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
#shape()
import numpy as np
arr=np.array([10,20,30,40,50],dtype=float)
print(arr)
print(arr.shape)

[10. 20. 30. 40. 50.]
(5,)


In [ ]:
#zeros()-to retuen n number of zeros
import numpy as np
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
#(m,n)-where m is how many times and n is which number
import numpy as np
arr=np.full(5,2)
print(arr)

[2 2 2 2 2]


In [ ]:
#for 2D
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
arr=np.full((2,3),11)
print(arr)

[[11 11 11]
 [11 11 11]]


In [ ]:
#for 3D
import numpy as np
arr=np.zeros((2,2,3))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
import numpy as np
arr=np.ones((2,2,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
import numpy as np
arr=np.full((2,2,3),9)
print(arr)

[[[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]]


In [ ]:
arr=np.arange(1,7)
print(arr)
new_arr=arr.reshape(3,2)
print(new_arr)
print(arr.reshape(6,1))

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
#2d
arr=np.ones((2,3))
print(arr)
print("______________")
new_arr=arr.reshape((3,2))
print(new_arr)

[[1. 1. 1.]
 [1. 1. 1.]]
______________
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3d
arr=np.ones((2,2,3))
print(arr)
print("______________")
new_arr=arr.reshape((6,2,1))
print(new_arr)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
______________
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]]


In [ ]:
#identity matrix
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.random.random(5)
print(arr)

[0.33443252 0.9335622  0.65816259 0.53671153 0.09377558]


In [ ]:
arr=np.random.randint(5)
print(arr)

1


In [ ]:
arr=np.random.random((5,3))
print(arr)

[[0.71302339 0.10116819 0.73096423]
 [0.47484314 0.68488905 0.00250743]
 [0.25098731 0.23602113 0.02907893]
 [0.03469829 0.63457454 0.61329832]
 [0.04479722 0.6294886  0.93597167]]


In [ ]:
arr=np.random.random((2,3,3))
print(arr)

[[[0.78422625 0.55818028 0.3008821 ]
  [0.49713963 0.07902736 0.89797893]
  [0.0396613  0.56791848 0.75165571]]

 [[0.39046207 0.75693092 0.00244148]
  [0.92797779 0.0496645  0.86192766]
  [0.6679272  0.91515135 0.01506865]]]


In [ ]:
#uniform(low,high,size)
arr=np.random.uniform(10,20,3)
print(arr)

[13.15812645 19.25636608 10.22410731]


In [ ]:
arr=np.random.uniform(10,20,(2,3))
print(arr)

[[19.71788398 10.84434727 16.79791611]
 [15.38324476 16.27165358 19.69187093]]


In [ ]:
#mean is 0 and SD is 1
arr=np.random.randn(2,3,3)
print(arr)

[[[ 0.22592539  0.64646262 -0.11116569]
  [-0.22490221  0.90068261  1.3674453 ]
  [ 0.07556034  0.38231059 -1.33058156]]

 [[-0.052968    1.35948556  1.16237191]
  [-1.29811234 -0.463529   -0.4571294 ]
  [ 0.36572232  0.52032001 -0.83333754]]]


In [ ]:
arr=np.arange(1,7)
print(arr)
result=np.random.choice(arr)
print(result)

[1 2 3 4 5 6]
4


In [ ]:
#seed()-random value is fixed
x=np.random.random(10)
np.random.seed(10)
print(x)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981]


In [ ]:
arr=np.random.randint(3,10)
print(arr)

5


In [ ]:
#shuffle()-the order is shuffled
arr=np.arange(1,11)
result=np.random.shuffle(arr)
print(arr)
print("--------")
print(result)


[ 3  5  7  9 10  1  4  8  2  6]
--------
None


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
new_arr=np.insert(arr,2,25)
print(new_arr)
n1=new_arr.delete(new_arr,2)
print(n1)
new_arr2=new_arr1.delete(new_arr,-1)
print(new_arr2)


[10 20 30 40 50]
[10 20 25 30 40 50]


AttributeError: 'numpy.ndarray' object has no attribute 'delete'

In [ ]:
# 2D row insertion
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
result=np.insert(arr,1,[100,200,300],axis=0)
print(result)

[[10 20 30]
 [40 50 60]]
[[ 10  20  30]
 [100 200 300]
 [ 40  50  60]]
[[10 20 30]]


In [ ]:
# 2D col insertion
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
result1=np.insert(arr,1,[100,200],axis=1)
print(result1)
# 2D row deletion
result=np.delete(result1,1,axis=1)
print(result)

[[10 20 30]
 [40 50 60]]
[[ 10 100  20  30]
 [ 40 200  50  60]]
[[10 20 30]
 [40 50 60]]


In [ ]:
# 2D sum
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[10 20 30]
 [40 50 60]]
[50 70 90]
[ 60 150]


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.min(arr))

[10 20 30 40 50]
10


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.max(arr))

[10 20 30 40 50]
50


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.mean(arr))

[10 20 30 40 50]
30.0


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.var(arr))

[10 20 30 40 50]
200.0


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.std(arr))

In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.percentile(arr,30))

[10 20 30 40 50]
22.0


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.percentile(arr,[20,30]))

[10 20 30 40 50]
[18. 22.]


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.percentile(arr,30))
print(np.quantile(arr,0.30))

[10 20 30 40 50]
22.0
22.0


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.argmax(arr))

[10 20 30 40 50]
4


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.argmin(arr))

[10 20 30 40 50]
0


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(np.log(arr))
print(np.log10(arr))
arr1=np.array([10,20,30,40,50])
print(arr1)
print(np.log10(arr1))

[1 2 3 4 5]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[10 20 30 40 50]
[1.         1.30103    1.47712125 1.60205999 1.69897   ]


In [ ]:
arr=np.array([4,9,16,25])
print(arr)
print(np.sqrt(arr))

In [ ]:
arr=np.array([10.256,9.78,16.21,25.92])
print(arr)
print(np.round(arr))
print(np.round(arr,3))

[10.256  9.78  16.21  25.92 ]
[10. 10. 16. 26.]
[10.256  9.78  16.21  25.92 ]


In [ ]:
#floor()-lowest value
arr=np.array([10.256,9.78,16.21,25.92])
print(arr)
print(np.floor(arr))


[10.256  9.78  16.21  25.92 ]
[10.  9. 16. 25.]


In [ ]:
#ceil()--highest value
arr=np.array([10.256,9.78,16.21,25.92])
print(arr)
print(np.ceil(arr))

[10.256  9.78  16.21  25.92 ]
[11. 10. 17. 26.]


In [ ]:
#abs()--absolute value always positive
arr=np.array([-10.256,9.78,-16.21,25.92])
print(arr)
print(np.abs(arr))

[-10.256   9.78  -16.21   25.92 ]
[10.256  9.78  16.21  25.92 ]


In [ ]:
arr=np.array([-10.256,9.78,-16.21,25.92])
print(arr)
print(np.sort(arr))

[-10.256   9.78  -16.21   25.92 ]
[-16.21  -10.256   9.78   25.92 ]


In [ ]:
arr=np.array([-10.256,9.78,-16.21,25.92])
print(arr)
print(np.sort(arr)[::-1])

[-10.256   9.78  -16.21   25.92 ]
[ 25.92    9.78  -10.256 -16.21 ]


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.min(arr))

[[10 20 30]
 [40 50 60]]
10


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.max(arr))

[[10 20 30]
 [40 50 60]]
60


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.mean(arr))

[[10 20 30]
 [40 50 60]]
35.0


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.var(arr))

[[10 20 30]
 [40 50 60]]
291.6666666666667


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.std(arr))

In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.percentile(arr,60))

[[10 20 30]
 [40 50 60]]
40.0


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.percentile(arr,60))
print(np.quantile(arr,0.40))

[[10 20 30]
 [40 50 60]]
40.0
30.0


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.argmax(arr))

[[10 20 30]
 [40 50 60]]
5


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.argmin(arr))

[[10 20 30]
 [40 50 60]]
0


In [ ]:
#default falue for log is e=2.71828
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.log10(arr))

[[10 20 30]
 [40 50 60]]
[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(np.sqrt(arr))

[[10 20 30]
 [40 50 60]]
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [ ]:
arr=np.array([[10.32,20.76,30.32],[40.09,50.43,60.98]])
print(arr)
print(np.round(arr))

[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]


In [ ]:
arr=np.array([[10.32,20.76,30.32],[40.09,50.43,60.98]])
print(arr)
print(np.floor(arr))

In [ ]:
arr=np.array([[10.32,20.76,30.32],[40.09,50.43,60.98]])
print(arr)
print(np.ceil(arr))

[[10.32 20.76 30.32]
 [40.09 50.43 60.98]]
[[11. 21. 31.]
 [41. 51. 61.]]


In [ ]:
arr=np.array([[10.32,-20.76,30.32],[-40.09,50.43,60.98]])
print(arr)
print(np.abs(arr))

[[ 10.32 -20.76  30.32]
 [-40.09  50.43  60.98]]
[[10.32 20.76 30.32]
 [40.09 50.43 60.98]]


In [ ]:
arr=np.array([[10.32,-20.76,30.32],[-40.09,50.43,60.98]])
print(arr)
print(np.sort(arr))

[[ 10.32 -20.76  30.32]
 [-40.09  50.43  60.98]]
[[-20.76  10.32  30.32]
 [-40.09  50.43  60.98]]


In [ ]:
arr=np.array([[10.32,-20.76,30.32],[-40.09,50.43,60.98]])
print(arr)
print(np.sort(arr)[::-1])

[[ 10.32 -20.76  30.32]
 [-40.09  50.43  60.98]]
[[-40.09  50.43  60.98]
 [-20.76  10.32  30.32]]


In [ ]:
#1
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [ ]:
#2
import numpy as np
arr=np.array([45,78,92,56,88,67,34])
print(np.min(arr))
print(np.max(arr))

34
92


In [ ]:
#3
import numpy as np
arr=np.array([12000,15000,18000,11000])
print(np.mean(arr))

14000.0


In [ ]:
#4
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.var(arr))

200.0


In [ ]:
#5
import numpy as np
arr=np.array([60,70,80,90,100])
print(np.std(arr))

In [ ]:
#6
import numpy as np
arr=np.array([35,42,55,60,68,72,80,85,95,100])
print(np.percentile(arr,50))

70.0


In [ ]:
#7
import numpy as np
arr=np.array([25000,30000,35000,40000,45000,50000])
print(np.quantile(arr,[0.25,0.75]))

[31250. 43750.]


In [ ]:
#8
import numpy as np
arr=np.array([15000,22000,18000,35000,27000,12000])
print(np.argmax(arr))

3


In [ ]:
#9
import numpy as np
arr=np.array([32,28,35,25,30,22,38])
print(np.argmin(arr))

5


In [ ]:
#10
import numpy as np
arr=np.array([1,10,100,1000,10000])
print(np.log10(arr))

[0. 1. 2. 3. 4.]


In [ ]:
#11
import numpy as np
arr=np.array([1,2,4,8,16,32])
print(np.log2(arr))

[0. 1. 2. 3. 4. 5.]


In [ ]:
#12
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
#13
import numpy as np
arr=np.array([4,9,16,25,36,49])
print(np.sqrt(arr))

[2. 3. 4. 5. 6. 7.]


In [ ]:
#14
import numpy as np
arr=np.array([12.45,23.67,45.89,56.12,78.95])
print(np.round(arr,1))

[12.4 23.7 45.9 56.1 79. ]


In [ ]:
#15
import numpy as np
arr=np.array([10.2,15.8,20.4,25.9,30.1])
print(np.floor(arr))

[10. 15. 20. 25. 30.]


In [ ]:
#16
import numpy as np
arr=np.array([10.2,15.8,20.4,25.9,30.1])
print(np.ceil(arr))

[11. 16. 21. 26. 31.]


In [ ]:
#17
import numpy as np
arr=np.array([-5000,3000,-2500,4500,-1000])
print(np.abs(arr))

[5000 3000 2500 4500 1000]


In [ ]:
#18
import numpy as np
arr=np.array([45,12,89,34,67,23])
print(np.sort(arr))

[12 23 34 45 67 89]


In [ ]:
#19
import numpy as np
arr=np.array(["Ravi","Anu","Kiran","Bala","Meena"])
print(np.sort(arr))

['Anu' 'Bala' 'Kiran' 'Meena' 'Ravi']


In [ ]:
#20
import numpy as np
arr=np.array([78,45,92,66,88,54,99])
print(np.sort(arr)[::-1])

[99 92 88 78 66 54 45]


In [ ]:
#concatenate()--joins to arrays and no change in dim
import numpy as np
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
print(np.concatenate((arr1,arr2)))

[10 20 30 40 50 60]


In [ ]:
#2D
arr1=np.arange(10,20).reshape(2,5)
arr2=np.arange(1,11).reshape(2,5)
print(arr1)
print(arr2)
print(np.concatenate((arr1,arr2)))

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#3D
arr2=np.arange(1,31).reshape(2,3,5)
arr3=np.arange(21,51).reshape(2,3,5)
print(arr2)
print(arr3)
print(np.concatenate((arr2,arr3)))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
[[[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]

 [[36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]

 [[36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [ ]:
arr1=np.arange(10,20).reshape(2,5)
arr2=np.arange(1,11).reshape(2,5)
print(arr1)
print(arr2)
print(np.concatenate((arr1,arr2),axis=1))

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10 11 12 13 14  1  2  3  4  5]
 [15 16 17 18 19  6  7  8  9 10]]


In [ ]:
arr1=np.arange(10,20).reshape(2,5)
arr2=np.arange(1,11).reshape(2,5)
print(arr1)
print(arr2)
print(np.concatenate((arr1,arr2),axis=0))

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr1=np.array([[10,20],[20,30]])
arr2=np.array([[10,20]])
print(arr1)
print(arr2)
print(np.concatenate((arr1,arr2)))

[[10 20]
 [20 30]]
[[10 20]]
[[10 20]
 [20 30]
 [10 20]]


In [ ]:
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(arr1)
print(arr2)
print(np.concatenate((arr1,arr2)))

[[10 20]
 [30 40]]
[[50 60]
 [70 80]]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [ ]:
#stack()--dimensions change
#1D
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
print(arr1)
print(arr2)
print(np.stack((arr1,arr2),axis=1))
print(np.stack((arr1,arr2),axis=0))
print(np.concatenate((arr1,arr2),axis=0))

[10 20 30]
[40 50 60]
[[10 40]
 [20 50]
 [30 60]]
[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [ ]:

#2D
arr1=np.arange(10,20).reshape(2,5)
arr2=np.arange(1,11).reshape(2,5)
print(arr1)
print(arr2)
print("---------")
print(np.stack((arr1,arr2),axis=0))
print("-----------")
print(np.stack((arr1,arr2),axis=1))

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
---------
[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
-----------
[[[10 11 12 13 14]
  [ 1  2  3  4  5]]

 [[15 16 17 18 19]
  [ 6  7  8  9 10]]]


In [ ]:
#3D
arr2=np.arange(1,31).reshape(2,3,5)
arr3=np.arange(21,51).reshape(2,3,5)
print(arr2)
print(arr3)
print(np.stack((arr2,arr3),axis=0))
print("----------")
print(np.stack((arr2,arr3),axis=1))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
[[[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]

 [[36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]
[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]]

  [[16 17 18 19 20]
   [21 22 23 24 25]
   [26 27 28 29 30]]]


 [[[21 22 23 24 25]
   [26 27 28 29 30]
   [31 32 33 34 35]]

  [[36 37 38 39 40]
   [41 42 43 44 45]
   [46 47 48 49 50]]]]
----------
[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]]

  [[21 22 23 24 25]
   [26 27 28 29 30]
   [31 32 33 34 35]]]


 [[[16 17 18 19 20]
   [21 22 23 24 25]
   [26 27 28 29 30]]

  [[36 37 38 39 40]
   [41 42 43 44 45]
   [46 47 48 49 50]]]]


In [ ]:

#vertical stacking
#1D
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
print(arr1)
print(arr2)
print(np.vstack((arr1,arr2)))
print("---------------")
#2D
arr1=np.arange(10,20).reshape(2,5)
arr2=np.arange(1,11).reshape(2,5)
print(arr1)
print(arr2)
print(np.vstack((arr1,arr2)))
print("-----------------")
#3D
arr2=np.arange(1,31).reshape(2,3,5)
arr3=np.arange(21,51).reshape(2,3,5)
print(arr2)
print(arr3)
print(np.vstack((arr2,arr3)))

[10 20 30]
[40 50 60]
[[10 20 30]
 [40 50 60]]
---------------
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-----------------
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
[[[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]

 [[36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]

 [[36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [ ]:
#horizontal stacking
#1D
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
print(arr1)
print(arr2)
print(np.hstack((arr1,arr2)))
print("---------------")
#2D
arr1=np.arange(10,20).reshape(2,5)
arr2=np.arange(1,11).reshape(2,5)
print(arr1)
print(arr2)
print(np.hstack((arr1,arr2)))
print("-----------------")
#3D
arr2=np.arange(1,31).reshape(2,3,5)
arr3=np.arange(21,51).reshape(2,3,5)
print(arr2)
print(arr3)
print(np.hstack((arr2,arr3)))

[10 20 30]
[40 50 60]
[10 20 30 40 50 60]
---------------
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10 11 12 13 14  1  2  3  4  5]
 [15 16 17 18 19  6  7  8  9 10]]
-----------------
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
[[[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]

 [[36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [ ]:
#vstack()
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
arr3=np.array([70,80,90])
print(arr1)
print(arr2)
print(arr3)
print(np.vstack((arr1,arr2,arr3)))
print("--------------")
#hstack()
print(np.hstack((arr1,arr2,arr3)))

[10 20 30]
[40 50 60]
[70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
--------------
[10 20 30 40 50 60 70 80 90]


In [ ]:
#split()
import numpy as np
arr=np.array([10,20,30,40,50,60,80,90,20])
print(np.split(arr,3))   #equal split
print(np.split(arr,[3,5]))  #position based
print(np.split(arr,[0,3,5]))

[array([10, 20, 30]), array([40, 50, 60]), array([80, 90, 20])]
[array([10, 20, 30]), array([40, 50]), array([60, 80, 90, 20])]
[array([], dtype=int64), array([10, 20, 30]), array([40, 50]), array([60, 80, 90, 20])]


In [ ]:
arr=np.array([[10,20],[30,40],[50,60],[70,80]])
print(arr)
print("___________________")
print(np.split(arr,4,axis=0))
print("------------------")
print(np.split(arr,2,axis=1))


[[10 20]
 [30 40]
 [50 60]
 [70 80]]
___________________
[array([[10, 20]]), array([[30, 40]]), array([[50, 60]]), array([[70, 80]])]
------------------
[array([[10],
       [30],
       [50],
       [70]]), array([[20],
       [40],
       [60],
       [80]])]
